services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - sya-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_DEBUG=INFO
      - OLLAMA_HOST=http://0.0.0.0:11434

  api:
    build:
      context: ./apps/api
    container_name: sya-api
    ports:
      - "3001:3001" 
    environment:
      - SERVER_ADDR=0.0.0.0:3001
      - OLLAMA_URL=http://ollama:11434/
    networks:
      - sya-net
    depends_on:
      - ollama

networks:
  sya-net:
    driver: bridge
